# configs/mapping_starai_to_bigarm.yaml

leader:
  name: "starai_arm_violin"
  joints:
    - "joint_1"
    - "joint_2"
    - "joint_3"
    - "joint_4"
    - "joint_5"
    - "joint_6"
    - "joint_7"

follower:
  name: "big_7dof_arm"
  joints:
    - "shoulder_pan_joint"
    - "shoulder_lift_joint"
    - "elbow_joint"
    - "wrist_1_joint"
    - "wrist_2_joint"
    - "wrist_3_joint"
    - "wrist_4_joint"

mapping:
  # follower_joint_name 기준
  sign:
    shoulder_pan_joint: 1.0
    shoulder_lift_joint: -1.0
    elbow_joint: 1.0
    wrist_1_joint: 1.0
    wrist_2_joint: 1.0
    wrist_3_joint: 1.0
    wrist_4_joint: 1.0

  scale:
    shoulder_pan_joint: 1.0
    shoulder_lift_joint: 1.0
    elbow_joint: 1.0
    wrist_1_joint: 1.0
    wrist_2_joint: 1.0
    wrist_3_joint: 1.0
    wrist_4_joint: 1.0

  offset:
    shoulder_pan_joint: 0.0
    shoulder_lift_joint: 0.0
    elbow_joint: 0.0
    wrist_1_joint: 0.0
    wrist_2_joint: 0.0
    wrist_3_joint: 0.0
    wrist_4_joint: 0.0

safety:
  position_min:
    shoulder_pan_joint: -2.5
    shoulder_lift_joint: -2.0
    elbow_joint: -2.5
    wrist_1_joint: -2.5
    wrist_2_joint: -2.5
    wrist_3_joint: -2.5
    wrist_4_joint: -2.5

  position_max:
    shoulder_pan_joint: 2.5
    shoulder_lift_joint: 2.0
    elbow_joint: 2.5
    wrist_1_joint: 2.5
    wrist_2_joint: 2.5
    wrist_3_joint: 2.5
    wrist_4_joint: 2.5

  vel_limit:
    shoulder_pan_joint: 1.5   # rad/s
    shoulder_lift_joint: 1.5
    elbow_joint: 1.5
    wrist_1_joint: 2.0
    wrist_2_joint: 2.0
    wrist_3_joint: 2.0
    wrist_4_joint: 2.0

  soft_margin: 0.05
